const loginPanel=document.querySelector("#loginPanel");const dashboard=document.querySelector("#dashboard");const loginForm=document.querySelector("#loginForm");const centerForm=document.querySelector("#centerForm");const logoutButton=document.querySelector("#logoutButton");let currentEmail="";let hasUnsavedChanges=false;
const escapeHtml=(value)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const formatDate=(value,withTime=true)=>value?new Intl.DateTimeFormat("ko-KR",withTime?{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}:{year:"numeric",month:"short",day:"numeric"}).format(new Date(value)):"-";
function showLogin(message=""){loginPanel.hidden=false;dashboard.hidden=true;logoutButton.hidden=true;document.querySelector("#loginMessage").textContent=message}
function formValues(){const data=new FormData(centerForm),values=Object.fromEntries(data.entries());values.categories=data.getAll("categories");return values}
function updatePreview(){const values=formValues();document.querySelector("#previewName").textContent=values.name||"센터명";document.querySelector("#previewArea").textContent=values.area||"지역";document.querySelector("#previewLead").textContent=values.lead||"센터 소개를 입력하면 이곳에 표시됩니다.";document.querySelector("#previewTherapist").textContent=values.therapist||"-";document.querySelector("#previewHours").textContent=values.opening_hours||"-";document.querySelector("#previewPrice").textContent=values.price||"-";const items=[...values.categories,...values.tags.split(",").map((tag)=>tag.trim()).filter(Boolean)].slice(0,6);document.querySelector("#previewTags").innerHTML=items.map((tag)=>`<span>${escapeHtml(tag)}</span>`).join("");document.querySelector('[data-count="lead"]').textContent=values.lead.length}
function syncCategories(center){const selected=new Set(center.categories||[]);centerForm.querySelectorAll('[name="categories"]').forEach((input)=>{input.checked=selected.has(input.value)})}
function profileStatus(center){const items=[{label:"센터 기본 정보",done:Boolean(center.name&&center.area&&center.address)},{label:"연락처와 운영시간",done:Boolean(center.phone&&center.openingHours)},{label:"소개와 전문 분야",done:Boolean(center.lead&&(center.tags||[]).length>=2)},{label:"가격 또는 상담 안내",done:Boolean(center.price&&center.conversion)}];const score=Math.round(items.filter((item)=>item.done).length/items.length*100);document.querySelector("#completionValue").textContent=`${score}%`;document.querySelector("#completionBar").style.width=`${score}%`;document.querySelector("#checklist").innerHTML=items.map((item)=>`<div class="${item.done?"done":""}"><i>${item.done?"✓":"·"}</i><span>${item.label}</span></div>`).join("")}
function fillDashboard(data){currentEmail=data.account?.email||currentEmail;loginPanel.hidden=true;dashboard.hidden=false;logoutButton.hidden=false;document.querySelector("#centerHeading").textContent=`${data.center.name} 운영 현황`;document.querySelector("#updatedAt").textContent=`최근 수정 ${formatDate(data.center.updatedAt,false)}`;document.querySelector("#views").textContent=data.totals.views.toLocaleString();document.querySelector("#contacts").textContent=data.totals.contactClicks.toLocaleString();document.querySelector("#contactRate").textContent=`${data.totals.contactRate||0}%`;document.querySelector("#last30Views").textContent=(data.totals.last30Views||0).toLocaleString();document.querySelector("#last30Contacts").textContent=(data.totals.last30Contacts||0).toLocaleString();document.querySelector("#reviews").textContent=data.totals.reviews.toLocaleString();document.querySelector("#rating").textContent=data.totals.ratingAverage?`${data.totals.ratingAverage} / 5`:'-';const fields={name:data.center.name,area:data.center.area,address:data.center.address,phone:data.center.phone,website:data.center.website,opening_hours:data.center.openingHours,lead:data.center.lead,tags:(data.center.tags||[]).join(", "),therapist:data.center.therapist,price:data.center.price,conversion:data.center.conversion};Object.entries(fields).forEach(([name,value])=>{centerForm.elements[name].value=value||""});profileStatus(data.center);updatePreview();document.querySelector("#eventList").innerHTML=data.recentEvents.map((item)=>`<article><strong>${item.type==="view"?"센터 상세 조회":"상담 연결 클릭"}</strong><span>${escapeHtml(item.source)} · ${formatDate(item.createdAt)}</span></article>`).join("")||'<p class="empty">아직 기록된 이용자 활동이 없습니다.</p>';document.querySelector("#reviewList").innerHTML=data.recentReviews.map((item)=>`<article><strong>${escapeHtml(item.nickname)}</strong><span class="stars">${"★".repeat(item.rating)}${"☆".repeat(5-item.rating)}</span><p>${escapeHtml(item.content)}</p><span>${formatDate(item.createdAt)}</span></article>`).join("")||'<p class="empty">아직 등록된 후기가 없습니다.</p>'}
async function loadDashboard(){const response=await fetch("/api/owner-dashboard");if(response.status===401)return showLogin();const data=await response.json().catch(()=>({}));if(!response.ok)return showLogin(data.error||"센터 정보를 불러오지 못했습니다.");syncCategories(data.center);fillDashboard(data)}
loginForm.addEventListener("submit",async(event)=>{event.preventDefault();const button=loginForm.querySelector("button");button.disabled=true;button.textContent="로그인 중…";const response=await fetch("/api/owner-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:document.querySelector("#email").value,password:document.querySelector("#password").value})});const data=await response.json().catch(()=>({}));button.disabled=false;button.textContent="대시보드 들어가기";if(!response.ok)return showLogin(data.error||"로그인하지 못했습니다.");document.querySelector("#password").value="";await loadDashboard()});
function setDirtyState(dirty){hasUnsavedChanges=dirty;const saveBox=centerForm.querySelector(".sticky-save"),button=centerForm.querySelector('[type="submit"]'),label=document.querySelector("#changeStatus");saveBox.classList.toggle("dirty",dirty);button.disabled=!dirty;label.textContent=dirty?"저장하지 않은 변경사항이 있습니다":"저장된 정보입니다"}
centerForm.addEventListener("input",()=>{updatePreview();setDirtyState(true)});centerForm.addEventListener("submit",async(event)=>{event.preventDefault();const status=document.querySelector("#saveStatus");const button=centerForm.querySelector('[type="submit"]');status.textContent="저장 중…";button.disabled=true;const body=formValues();body.tags=body.tags.split(",").map((tag)=>tag.trim()).filter(Boolean);const response=await fetch("/api/owner-dashboard",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));button.disabled=false;if(response.status===401)return showLogin("로그인 시간이 만료되었습니다. 다시 로그인해 주세요.");if(!response.ok){status.textContent=data.error||"저장하지 못했습니다.";return}fillDashboard({...data,account:{email:currentEmail}});setDirtyState(false);status.textContent="✓ 저장되었습니다";setTimeout(()=>{status.textContent=""},2500)});
document.querySelectorAll("[data-jump-profile]").forEach((button)=>button.addEventListener("click",()=>document.querySelector("#profile").scrollIntoView({behavior:"smooth"})));logoutButton.addEventListener("click",async()=>{await fetch("/api/owner-logout",{method:"POST"});showLogin("안전하게 로그아웃되었습니다.")});loadDashboard();
document.querySelector("#togglePassword").addEventListener("click",()=>{const password=document.querySelector("#password"),show=password.type==="password";password.type=show?"text":"password";document.querySelector("#togglePassword").textContent=show?"숨기기":"보기"});window.addEventListener("beforeunload",(event)=>{if(!hasUnsavedChanges)return;event.preventDefault();event.returnValue=""});
