const loginPanel=document.querySelector("#loginPanel");const dashboard=document.querySelector("#dashboard");const loginForm=document.querySelector("#loginForm");const centerForm=document.querySelector("#centerForm");const logoutButton=document.querySelector("#logoutButton");
const escapeHtml=(value)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const formatDate=(value)=>new Intl.DateTimeFormat("ko-KR",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value));
function showLogin(message=""){loginPanel.hidden=false;dashboard.hidden=true;logoutButton.hidden=true;document.querySelector("#loginMessage").textContent=message}
function fillDashboard(data){loginPanel.hidden=true;dashboard.hidden=false;logoutButton.hidden=false;document.querySelector("#centerHeading").textContent=`${data.center.name} 관리`;document.querySelector("#accountEmail").textContent=data.account.email;document.querySelector("#views").textContent=data.totals.views.toLocaleString();document.querySelector("#contacts").textContent=data.totals.contactClicks.toLocaleString();document.querySelector("#reviews").textContent=data.totals.reviews.toLocaleString();document.querySelector("#rating").textContent=data.totals.ratingAverage?`${data.totals.ratingAverage} / 5`:'-';const fields={name:data.center.name,area:data.center.area,address:data.center.address,phone:data.center.phone,website:data.center.website,opening_hours:data.center.openingHours,lead:data.center.lead,tags:(data.center.tags||[]).join(", "),therapist:data.center.therapist,price:data.center.price,conversion:data.center.conversion};Object.entries(fields).forEach(([name,value])=>{centerForm.elements[name].value=value||""});document.querySelector("#eventList").innerHTML=data.recentEvents.map((item)=>`<article><strong>${item.type==="view"?"센터 상세 조회":"상담 버튼 클릭"}</strong><span>${escapeHtml(item.source)} · ${formatDate(item.createdAt)}</span></article>`).join("")||'<p class="empty">아직 이용자 활동이 없습니다.</p>';document.querySelector("#reviewList").innerHTML=data.recentReviews.map((item)=>`<article><strong>${escapeHtml(item.nickname)}</strong><span class="stars">${"★".repeat(item.rating)}${"☆".repeat(5-item.rating)}</span><p>${escapeHtml(item.content)}</p><span>${formatDate(item.createdAt)}</span></article>`).join("")||'<p class="empty">아직 등록된 후기가 없습니다.</p>'}
async function loadDashboard(){const response=await fetch("/api/owner-dashboard");if(response.status===401)return showLogin();const data=await response.json().catch(()=>({}));if(!response.ok)return showLogin(data.error||"센터 정보를 불러오지 못했습니다.");fillDashboard(data)}
loginForm.addEventListener("submit",async(event)=>{event.preventDefault();const button=loginForm.querySelector("button");button.disabled=true;const response=await fetch("/api/owner-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:document.querySelector("#email").value,password:document.querySelector("#password").value})});const data=await response.json().catch(()=>({}));button.disabled=false;if(!response.ok)return showLogin(data.error||"로그인하지 못했습니다.");document.querySelector("#password").value="";await loadDashboard()});
centerForm.addEventListener("submit",async(event)=>{event.preventDefault();const status=document.querySelector("#saveStatus");status.textContent="저장 중…";const form=new FormData(centerForm);const body=Object.fromEntries(form.entries());body.tags=body.tags.split(",").map((tag)=>tag.trim()).filter(Boolean);const response=await fetch("/api/owner-dashboard",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(response.status===401)return showLogin("다시 로그인해 주세요.");if(!response.ok){status.textContent=data.error||"저장하지 못했습니다.";return}fillDashboard({...data,account:{email:document.querySelector("#accountEmail").textContent}});status.textContent="저장되었습니다";setTimeout(()=>{status.textContent=""},2500)});
logoutButton.addEventListener("click",async()=>{await fetch("/api/owner-logout",{method:"POST"});showLogin("로그아웃되었습니다.")});loadDashboard();
