const API_BASE=window.location.origin;
const form=document.querySelector("#registrationForm");
const message=document.querySelector("#formMessage");
const submitButton=document.querySelector("#submitButton");
const licenseFields=document.querySelector("#licenseFields");
const licenseFileInput=document.querySelector("#licenseFileInput");
const licenseImagePathInput=document.querySelector("#licenseImagePathInput");
const photoFileInput=document.querySelector("#photoFileInput");
const photoPathInput=document.querySelector("#photoPathInput");
const photoPathsInput=document.querySelector("#photoPathsInput");
let currentStep=1;

function showStep(step){currentStep=step;document.querySelectorAll(".form-step").forEach(el=>el.classList.toggle("active",Number(el.dataset.step)===step));document.querySelectorAll("[data-step-dot]").forEach(el=>{const n=Number(el.dataset.stepDot);el.classList.toggle("active",n===step);el.classList.toggle("done",n<step)});if(step===3)renderSummary();window.scrollTo({top:360,behavior:"smooth"})}
function isTherapistBackground(){return new FormData(form).get("therapistBackground")==="yes"}
function syncBackground(){const yes=isTherapistBackground();licenseFields.hidden=!yes;licenseFields.querySelectorAll("input").forEach(input=>input.required=yes)}
function validateStep(step){const panel=document.querySelector(`[data-step="${step}"]`);if(step===2&&!document.querySelector('[name="specialties"]:checked')){alert("전문 분야를 하나 이상 선택해주세요.");return false}const invalid=[...panel.querySelectorAll("input,textarea")].find(el=>!el.checkValidity());if(invalid){invalid.reportValidity();invalid.focus();return false}return true}
function renderSummary(){const data=new FormData(form);const specialties=[...document.querySelectorAll('[name="specialties"]:checked')].map(el=>el.value).join(", ");const rows=[["센터명",data.get("centerName")],["대표자",data.get("ownerName")],["전화번호",data.get("phone")],["이메일",data.get("email")],["주소",data.get("address")],["물리치료사 출신",isTherapistBackground()?"예":"아니오"],["전문 분야",specialties],["운영 시간",data.get("hours")||"미입력"]];document.querySelector("#reviewSummary").innerHTML=rows.map(([k,v])=>`<dt>${k}</dt><dd>${String(v||"").replaceAll("<","&lt;")}</dd>`).join("")}
function validateImage(file,required=false){if(!file&&!required)return;if(!file)throw new Error("확인 서류를 선택해주세요.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("JPG, PNG, WEBP 이미지만 올릴 수 있습니다.");if(file.size>3*1024*1024)throw new Error("이미지는 3MB 이하로 올려주세요.")}
async function upload(file,kind){if(!file)return"";const response=await fetch(`${API_BASE}/api/uploads?kind=${encodeURIComponent(kind)}`,{method:"POST",headers:{"Content-Type":file.type,"X-Movemap-Client":"register"},body:file});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"이미지 업로드에 실패했습니다.");return data.path}
function mapUrl(address){return address?`https://map.naver.com/p/search/${encodeURIComponent(address)}`:""}

document.querySelectorAll('[name="therapistBackground"]').forEach(el=>el.addEventListener("change",syncBackground));
document.querySelectorAll("[data-next]").forEach(button=>button.addEventListener("click",()=>{if(validateStep(currentStep))showStep(Number(button.dataset.next))}));
document.querySelectorAll("[data-prev]").forEach(button=>button.addEventListener("click",()=>showStep(Number(button.dataset.prev))));

form.addEventListener("submit",async event=>{event.preventDefault();if(!validateStep(3))return;message.textContent="";submitButton.disabled=true;submitButton.textContent="신청 중...";try{const photoFiles=[...photoFileInput.files].slice(0,5);if(photoFileInput.files.length>5)throw new Error("센터 사진은 최대 5장까지 올릴 수 있습니다.");photoFiles.forEach(file=>validateImage(file));const licenseFile=licenseFileInput.files[0];validateImage(licenseFile,isTherapistBackground());const photoPaths=[];for(const file of photoFiles)photoPaths.push(await upload(file,"center-photo"));photoPathInput.value=photoPaths[0]||"";photoPathsInput.value=JSON.stringify(photoPaths);licenseImagePathInput.value=await upload(licenseFile,"license");const data=new FormData(form);const address=String(data.get("address")||"");const payload={centerName:data.get("centerName"),ownerName:data.get("ownerName"),phone:data.get("phone"),email:data.get("email"),area:address.split(" ").slice(0,2).join(" "),address,naverMapUrl:mapUrl(address),lat:"",lng:"",website:"",photoUrl:"",photoPath:photoPathInput.value,photoPaths,licenseHolderName:isTherapistBackground()?data.get("licenseHolderName"):"해당 없음",licenseNumber:isTherapistBackground()?data.get("licenseNumber"):"해당 없음",licenseImagePath:isTherapistBackground()?licenseImagePathInput.value:"not-applicable",services:[...document.querySelectorAll('[name="specialties"]:checked')].map(el=>el.value).join(", "),memo:[data.get("hours"),data.get("memo")].filter(Boolean).join("\n"),consent:data.get("consent")==="on",therapistBackground:isTherapistBackground()};const response=await fetch(`${API_BASE}/api/center-applications`,{method:"POST",headers:{"Content-Type":"application/json","X-Movemap-Client":"register"},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"등록 신청에 실패했습니다.");form.reset();syncBackground();showStep(1);message.textContent="등록 신청이 접수되었습니다. 검토 후 안내드리겠습니다.";message.className="message success"}catch(error){message.textContent=error.message||"서버 연결을 확인해주세요.";message.className="message error"}finally{submitButton.disabled=false;submitButton.textContent="등록 신청하기"}});
syncBackground();
